### ISSUE TITLE
Deleting Item Error Message

### ISSUE THREAD

**Issue by deanseeman** [UVicLibrary/Vault#24]
At the bottom of a Work metadata record I tried to add a new Item and delete the old one. When under Items I try to select Delete from the Action drop down:
![image](https://user-images.githubusercontent.com/17652528/58720569-62a03180-8387-11e9-8874-9f478158e2c4.png)

I get the following error:

![image](https://user-images.githubusercontent.com/17652528/58719663-1d7b0000-8385-11e9-8dd8-ced4e39b8db3.png)

I really just want to replace the file/item for the work so maybe there's a better way to do this.

**Comment by eltiffster** [comment]
I believe this issue is fixed anyway, but for future reference: if you just want to replace the file, you can upload a new version (see [instructions here](https://github.com/UVicLibrary/Vault/wiki/Changing-Files-or-Versions#switching-versions-through-the-interface).
