### ISSUE TITLE
Collection mapping issue

### ISSUE THREAD

**Issue by KarenDykes** [UVicLibrary/Vault#26]
### Descriptive summary

I'm getting the attached error message when trying to generate a CSV after mapping the vault fields. 

[Vault_Collection_Mapping_Issue_SamMaclure.pdf](https://github.com/UVicLibrary/Vault/files/3312159/Vault_Collection_Mapping_Issue_SamMaclure.pdf)

**Comment by sephirothkod** [comment]
This has been fixed in production
