### ISSUE TITLE
Edit Collection: Model mismatch error

### ISSUE THREAD

**Issue by lisa-goddard** [UVicLibrary/Vault#28]
### Descriptive summary

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

I am currently unable to edit Collections, which means I can't add a thumbnail & description for the Collection, and I can't add it as a homepage feature. E.g. Sessional clippings, Fire insurance plans

### Expected behavior

Should be able to select Edit from the dropdown menu at the collection level and access the "Edit Collection" functionality. 

### Actual behavior

Throws an error: Model mismatch. Expected GenericWork. Got: Collection. 

### Steps to reproduce the behavior

In the dashboard select Collections, All Collections. Click on the  "British Columbia Legislative Assembly Sessional Clippings Books" collection or the "Victoria Fire Insurance Plans".
![vault_EditCollection](https://user-images.githubusercontent.com/18603518/60726117-511feb80-9f2a-11e9-969b-0d671fa8d8f3.jpg)

### Related work

Link to related tickets or prior related work here.

**Comment by eltiffster** [comment]
Sorry, that was me playing with the breadcrumbs. It should be fine now.
