### ISSUE TITLE
Error message when mapping collections

### ISSUE THREAD

**Issue by KarenDykes** [UVicLibrary/Vault#31]
![Medieval_Mapping Error Message](https://user-images.githubusercontent.com/41589973/66404974-44ce8300-e99e-11e9-857a-6c7a8ea77968.PNG)

I get this error message after pressing the "choose mappings" button in Vault for the Medieval Manuscript collection. Dean said he got the same message with other collections when he tried to map them as well. 

Thanks for your help!

**Comment by sephirothkod** [comment]
Forgot to close. This was an issue with the connection to the remote drive.
