### ISSUE TITLE
Error when removing term from search results

### ISSUE THREAD

**Issue by lisa-goddard** [UVicLibrary/Vault#32]
### Descriptive summary

Do a search for any term (e.g. dickens). You see the results screen. Now remove the "dickens" term using the red x in the tab beside the search terms. This error appears.

This error appeared right after the Solr index problem late Oct 2019. 

### Rationale
![vault_error](https://user-images.githubusercontent.com/18603518/67729813-ca4abf00-f9af-11e9-994a-c9df51afa3bd.jpg)

### Expected behavior

Should return to a clean search screen with all results displayed. 

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by sephirothkod** [comment]
Fixed. Issues was with incorrect rights statements being uploaded during batch uploads
