### ISSUE TITLE
Issues with manually adding individual items to a collection

### ISSUE THREAD

**Issue by KarenDykes** [UVicLibrary/Vault#34]
I was trying to manually add a work to the Medieval and Early Modern Manuscripts collection but ran into some problems when I tried to upload the files. All the things on the Descriptions tab worked super well for entering the info but when I dragged and dropped in the folder of tif files, it would think for a bit for each file and then have an internal server area and move on to trying to add the next file, scrolling down the file list I noticed we also exceeded the maximum number of files to add at once. 

I tried to add just one file at a time because the problem could have been how large the folder was that I was trying to add and it looked like it was working but as soon as the file finished loading it had an error and disappeared and the all info on the Description tab also got erased. 

![Maximum no  of files exceeded (adding manually)](https://user-images.githubusercontent.com/41589973/69459119-e418c100-0d25-11ea-97e8-9f4100a512d1.PNG)

![Individually adding files error](https://user-images.githubusercontent.com/41589973/69459111-dfeca380-0d25-11ea-959f-8db304aa6b3f.PNG)

**Comment by sephirothkod** [comment]
Looks to be resolved for now. Seems to be just a coincidence with us making modifications to the server and doing reboots
