### ISSUE TITLE
"Gallery" view not working at collection level

### ISSUE THREAD

**Issue by lisa-goddard** [UVicLibrary/Vault#5]
### Descriptive summary

When changing layout to "Gallery" view from the main page of the Victorian Serial Novels collection I click the button and get an error message. 

### Expected behavior

View changes, no error. 

### Actual behavior

![vault_bug1](https://user-images.githubusercontent.com/18603518/37794485-d7a91bfa-2dce-11e8-88e5-ad3281f2bf7e.JPG)

![vault_bug1_error](https://user-images.githubusercontent.com/18603518/37794492-e2dba3e4-2dce-11e8-95ee-59aaf6708380.JPG)

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by sephirothkod** [comment]
@lisa-goddard This is an issue with the rights statement (weirdly enough). It is trying to pull the rights statements from the authority but we have imported creative commons statements from CDM when the authority is looking for rightsstatements.org statements.

**Comment by sephirothkod** [comment]
I have added the CC statement to the authority as a temporary fix. once we settle on the rights statements that we are going to use I'll run a script to change everything.
