### ISSUE TITLE
Extent field appears twice in work-level metadata view

### ISSUE THREAD

**Issue by lisa-goddard** [UVicLibrary/Vault#7]
### Descriptive summary

Extent note appears twice in metadata record view. The note exists only once in the record, so I think that this is just a display problem. 

### Expected behavior

Extent note would appear only once. 

### Actual behavior
At the work (issue) level in the Victorian Serials collection:

![vault_bug2](https://user-images.githubusercontent.com/18603518/37795419-a7799c7c-2dd1-11e8-9ac0-027e4f590fcb.JPG)

![vault_bug2_error](https://user-images.githubusercontent.com/18603518/37795458-bfb587b0-2dd1-11e8-9e04-6ef6686e601f.JPG)

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by sephirothkod** [comment]
This was in the list twice, it was included in the original metadata then we added it as a part of our metadata profile. It should be fixed now.
